### ISSUE TITLE
Wie wichtig ist uns Sicherheit?

### ISSUE THREAD

**Issue by Sta7e** [johanngoltz/sumz-ui#15]
Ich habe meine Entwicklungsumgebung mal wieder neu (und hoffentlich endlich mal sauber) eingerichtet. Als ich unseren *master*-branch getestet habe, ist mir folgendes aufgefallen:

#### Ausgabe von ``npm install`` (gekürzt):

``
[!] 23 vulnerabilities found [21929 packages audited]
    Severity: 10 Low | 8 Moderate | 5 High
    Run `npm audit` for more detail
`` 

``npm audit`` liefert den detaillierten [output](https://github.com/johanngoltz/sumz-ui/files/2023513/npm_audit_log.txt).

### Diskussion
Die Frage die sich mir jetzt stellt ist, ob und wie stark wir uns mit Sicherheitsaspekten auseinandersetzen?

Mögliche Ideen:
 - Bei jedem merge in den *master*-branch muss ``npm audit`` clean sein
 - Wir legen nach jedem Milestone eine Runde Security Patches ein und sorgen dann dafür, dass ``npm audit`` clean ist
 - Wir ignorieren das erst einmal und kümmern uns am Ende darum 
 - Wir ignorieren das komplett

Wie seht ihr das? Was sind eure Ideen?

**Comment by johanngoltz** [comment]
Da npm audit nichts weiter macht als die installierten Pakete auf bekannte Sicherheitslücken zu untersuchen, und die Lösung immer ein Update des betroffenen Pakets ist, denke ich, dass wir das gut als Bedingung für einen merge nehmen können. Schließlich sollte sich da nicht so oft etwas neues ergeben.

Ein Problem ergibt sich dabei aber: Was, wenn für eine Sicherheitslücke kein Fix bereitsteht? Konsequent dürften wir dann nicht "ausliefern", bis sie geschlossen ist...

**Comment by schaefermichael** [comment]
-> npm audit, aber keine Integration ins CI
