### ISSUE TITLE
Infrastruktur abklären

### ISSUE THREAD

**Issue by tomastepa** [johanngoltz/sumz-ui#16]
- SSL Verschlüsselung
- Webserver mit JRE und Python Laufzeitumgebung
- Datenbank (Was ist hier möglich?) SQL oder MySQL
- Können noreply-Mails versendet werden?

**Comment by tomastepa** [comment]
Windows-Server steht bereit und ist erreichbar über RDP innerhalb des DHBW-Netzes (evtl. VPN verwenden) unter **sumz1718.dh-karlsruhe.de** (IP 193.196.7.200).

**Wichtig**: Benutzerzugänge müssen erst eingerichtet werden. Wenn Zugang benötigt wird, bitte bei mir melden. Die Anmeldedaten sind dann die DHBW-Zugangsdaten.

**Comment by johanngoltz** [comment]
Was könnten wir auf diesem Server tun? Welches VPN meinst du?

**Comment by tomastepa** [comment]
Zur ersten Frage: So wie ich das sehe, können wir mit dem Server alles tun (bis auf den Mailversand). Das ist ein cleaner Windows-Server.

Zur zweiten Frage: Es gibt von der DH ein VPN mit dem du dich ins Netz einwählen kannst. 
[Flyer-VPN-in-der-Lehre.pdf](https://github.com/johanngoltz/sumz-ui/files/2077459/Flyer-VPN-in-der-Lehre.pdf)

**Comment by tomastepa** [comment]
**noreply-Mails:** Unser Server ist nun auf dem DHBW SMPT Relay (smpt.dh-karlsruhe.de) freigegeben.
Bitte den Port 25 verwenden.
