### ISSUE TITLE
Schnittstellen definieren

### ISSUE THREAD

**Issue by tomastepa** [johanngoltz/sumz-ui#17]
Schnittstellen zwischen Backend und UI definieren

**Comment by johanngoltz** [comment]
Dazu gehört auch, zu klären, wie Im- und Export ablaufen.

**Comment by johanngoltz** [comment]
Die Szenario-Entität benötigt noch ein bool-Flag `isActive`, das angibt, ob es in der Ergebnisdarstellung des Projekts standardmäßig angezeigt werden soll oder nicht.

**Comment by schaefermichael** [comment]
Vorläufige Definition Backend 
[api definition.docx](https://github.com/johanngoltz/sumz-ui/files/2089313/api.definition.docx)
