### ISSUE TITLE
Scenario-detail-Seite

### ISSUE THREAD

**Issue by schaefermichael** [johanngoltz/sumz-ui#18]
- [x] UI-Konzept mit Mockups für die Seite
- [x] Auswahl einer Chartlib (bspw. nvd3, chart.js,...)
- [x] Anbindung an Backend-Services
- [x] Grundstruktur für Anzeige eingegebener Daten
- [x] Anzeige der Ergebnisse im Diagramm
- [x] Schön machen
- [ ] Konfiguration des Diagramms
- [ ] User-Tests

Entwicklungsarbeit siehe [scenario-detail-page](https://github.com/johanngoltz/sumz-ui/tree/dev/scenario-detail-page)

**Comment by langerschris** [comment]
erstes Mockup erstellt 
siehe https://app.moqups.com/langerschris@gmail.com/s7EfXmdfqD/view/page/a58549ac4

**Comment by johanngoltz** [comment]
Vielen Dank, @langerschris. Hier sind meine Gedanken dazu:

- Die Seite wird wahrscheinlich meistens in 16:9 betrachtet werden, manchmal vielleicht auch 1:1 (halbe Bildschirmbreite). Ich denke, dass wir dafür optimieren sollten.
- Ein Nutzer kann die ihm angezeigten Diagramme konfigurieren. 
  - Kann er auch auswählen, welche ihm angezeigt werden? Wenn ja, welche? 
  - Wie weit soll die Konfigurierbarkeit gehen? Bspw. mehrere Kennzahlen in einem kombinierten Diagramm, ...
- Szenarien tauchen im Entwurf an drei verschiedenen Stellen auf. Schaffen wir es, das auf eine (die Tabelle) zu reduzieren?
- Ich würde vielleicht die Tabelle zu den eingegebenen FK- & CF-Werten nach Parameter und Jahr, und erst danach nach Szenarien gruppieren.

**Comment by Sta7e** [comment]
#40
