### ISSUE TITLE
Doku

### ISSUE THREAD

**Issue by schaefermichael** [johanngoltz/sumz-ui#21]

**Comment by Sta7e** [comment]
Soweit habe ich alle benötogten Dokumente angelegt und mit einer ersten Grobstruktur (Überschriften, teilweise TODOs) versehen. Jetzt müssen wir abklären, wer sich um welches Dokument kümmert. Es wäre außerdem gut, wenn noch einmal jemand drüber schaut, ob ich irgendetwas vergessen habe

**Comment by tomastepa** [comment]
Hier noch ein paar Links für die Doku:

Angular
https://angular.io/
Angular CLI
https://cli.angular.io/
Material Design Doku
https://material.angular.io/components/categories
Icons (die in Material Design Library verfügbar sind)
https://material.io/tools/icons/?style=baseline
ReactiveJS Doku
https://rxjs-dev.firebaseapp.com/api
Sandbox Mockserver Doku
https://getsandbox.com/docs/getting-started
