### ISSUE TITLE
Datenschutz

### ISSUE THREAD

**Issue by Philipp-frietsch93** [johanngoltz/sumz-ui#24]
Eckpunkte zum Datenschutz mit den Verantwortlichen abklären

**Comment by tomastepa** [comment]
Herr Pahl ist auf Datenschutz gebrieft
Prof. Freudenmann ist Datenschutzbeauftragter

**Comment by JackieChan66** [comment]
Gespeicherte Daten

Datenverzeichnis
- Wie lange werden die Daten gespeichert?
- Welche Daten gespeichert: Email, Passwort, Unternehmensdaten.
- Wer hat Zugriff auf den Server und auf die Daten?
- Impressum

Was muss dokumentiert werden.

**Comment by tomastepa** [comment]
@JackieChan66 wie weit seid ihr mit dem Thema? Ist das noch aktuell?

**Comment by JackieChan66** [comment]
@tomastepa, @langerschris und ich haben mal ein Dokument erstellt. Das sollte soweit passen.
Ich weiß allerdings nicht ob es überhaupt noch relevant ist
