### ISSUE TITLE
OptionsService

### ISSUE THREAD

**Issue by johanngoltz** [johanngoltz/sumz-ui#28]

**Comment by johanngoltz** [comment]
Status: existiert und funktioniert, die Einstellungen werden aber nicht persistiert, solange vom Backend keine Speichermöglichkeit dafür bereitgestellt wird.

**Comment by Sta7e** [comment]
Es wird vom Backend-Team keinen Blob-Store geben. Deswegen speichern wir das ganze lokal, was @johanngoltz  dankenswerterweise in #50 umgesetzt hat
