### ISSUE TITLE
Pflichtenheft

### ISSUE THREAD

**Issue by johanngoltz** [johanngoltz/sumz-ui#3]

**Comment by langerschris** [comment]
Erster Entwurf. Ergänzung durch Screenshots, Prototypen wünschenswert
[Pflichtenheft SUMZ UI.docx](https://github.com/johanngoltz/sumz-ui/files/2002741/Pflichtenheft.SUMZ.UI.docx)

**Comment by tomastepa** [comment]
Vorschlag für Änderungen am Pflichtenheft. Bitte überprüfen und ggf. annehmen.
Außerdem wurde ein Mockup eingefügt. Bitte um Feedback und ggf. Anpassung.
[Pflichtenheft.SUMZ.UI.docx](https://github.com/johanngoltz/sumz-ui/files/2009171/Pflichtenheft.SUMZ.UI.docx)

**Comment by johanngoltz** [comment]
Weitere Änderungen von mir: [Pflichtenheft SUMZ UI.docx](https://github.com/johanngoltz/sumz-ui/files/2009827/Pflichtenheft.SUMZ.UI.docx)

Finde @tomastepa|s Anpassungen gut. Ist ein Mockup unbedingt erforderlich? Wenn ja, sollte es dann auch den gesamtem Umfang der im Pflichtenheft genannten Anforderungen abdecken?

Und wer würde freiwillig ein UML-Diagramm erstellen?

**Comment by Sta7e** [comment]
Hier mal meine Anmerkungen/Ideen/Fragen:

#### 1.1
> Die Technische Spezifikation wird als separates Dokument erstellt.

Geben wir die Spec gemeinsam mit dem Pflichtenheft hab?

#### 1.2
> Im Rahmen dieses Projekts soll die Nutzeroberfläche bezüglich des Designs und der Funktionalität vollständig überarbeitet werden

Unser *muss* ist der Nachbau der aktuellen Funktionalität. Das *soll* / *kann* ist die Erweiterung. Passt das zu diesem Satz?

> ... das durch eine flache Lernkurve zukünftigen Projektgruppen den Einstieg einfacher macht ...

Wir wollen eine steile Lernkurve?! Also dass man schnell viel lernt. Die Einstiegshürde soll flach sein.

#### 2.1
> Dabei kann das Paket einen Teil beinhalten, der auf einem Server ausgeführt wird.

Das Paket soll einen lokalen Server starten, der die Funktionalität zu Verfügung stellt.

#### 3.1
> Das Design der Oberfläche ist an das Design der Software aus dem Projektjahr 2015/16 angelehnt. Die Oberfläche kann wie folgt aussehen:

Brauchen wir Mock-Ups, wenn wir sagen, dass wir uns an 15/16 orientieren? Sollen wir nicht eher bei dem Usertests mit reinschreiben, dass wir die Oberfläche iterativ entwickeln und verbessern? 
An sonsten stimme ich @johanngoltz zu: Wenn wir Mock-Ups machen, dann sollten die für alle Aspekte vorhanden sein.

#### 3.8
Müssen wir wirklich lokal speichern? War das je geplant?

#### 3.10
Login ist *muss* wenn das *soll* **Speichern auf Server** (3.8) umgesetzt wird, an sonsten eher ein *kann*

**Comment by johanngoltz** [comment]
> Müssen wir wirklich lokal speichern? War das je geplant?

_Ergebnisse_ müssen eigentlich gar nicht gespeichert werden, nur exportiert. 

Projekte (mit Szenarien, U-Daten,...) sollten auf dem Server persistiert werden. Das fehlt im Pflichtenheft bisher. Da die Backendleute der Ansicht waren, damit evtl. überfordert zu sein, könnten wir es vielleicht als "Nutzereingaben sollen auf dem Server gespeichert werden. Wird dies nicht umgesetzt, muss eine lokale Persistenz umgesetzt werden" formulieren?

**Comment by schaefermichael** [comment]
IMO ist die Speicherung von Eingabedaten ein Muss-Kriterium, die Sicherung der Ergebnisse ein Soll-Kriterium. Dass diese Daten serverseitig gespeichert werden, wäre für mich ein weiteres Soll-Kriterium. Ich würde diese drei Anforderungen so unter 3.8 listen.
In-/Export würde ich als eigenständige Kriterien definieren, da wir dies ohnehin genauer definieren sollten (Welche Daten und Formate?)

Ich finde 2.3 und 2.4 auch sehr vage gehalten, da kann man viel mehr interpretieren. Bei 2.3 könnten wir beispielsweise einen einheitlichen Codestil (enforced mit linting), die Beachtung frameworkspezifischer Best Practices und verständliches Naming listen.

**Comment by johanngoltz** [comment]
> 2.3 und 2.4

Finde es gut, das genauer zu spezifizieren. Würde noch Doku und Einhaltung der OOP-Prinzipien hinzufügen.

> IMO ist die Speicherung von Eingabedaten ein Muss-Kriterium

Sehe ich auch so.

> die Sicherung der Ergebnisse

ist doch nicht nötig, weil sie jederzeit wieder neu berechnet werden könnten - außer, das dauert viel zu lange, dann doch ein Soll-Kriterium. Vielleicht setzen wir im Pflichtenheft eine Zeitbegrenzung für die Berechnung, ab der die Ergebnisse gecacht werden müssen?

> In-/Export würde ich als eigenständige Kriterien definieren

ja.

**Comment by schaefermichael** [comment]
>>  die Sicherung der Ergebnisse
> ist doch nicht nötig, weil sie jederzeit wieder neu berechnet werden könnten - außer, das dauert viel zu lange, dann doch ein Soll-Kriterium.
Ich glaube, dass es gerade bei mehreren Szenarien dann langsam wird, wobei das natürlich auch von den Nutzereinstellungen abhängt. Aber das ganze kostet uns ja nichts (nur dem Backendteam) und ist ja letztendlich ressourcensparsam, was entweder der Nutzer (oder bei Umsetzung 2.2 die DH) merkt.
Auch im Bezug auf die REST-Prinzipien finde ich eine Persistierung als Attribut des Szenarios die vernünftigste Lösung.
tl;dr: Ich will das haben, das Backendteam muss das halt irgendwie hinbekommen.

**Comment by Sta7e** [comment]
Wir müssen auch noch Meilensteine festlegen.

- Präsentation ist am 09.07. An diesem Tag sollten wir das Projekt als solches fertig haben
- Wir könnten versuchen, die Abgabe aller Artefakte auf das Ende der Woche (13.07) festzulegen 

- Ein möglicher Meilenstein wäre ein erster funktionsfähiger Prototyp für Usertests.
- Darauf folgend das abschließen der nächste Iteration als weiterer Meilenstein
- Wir sollten auf jeden Fall auch einen Zwischenstand den Kunden vorstellen (ca. Halbzeit) und das als Meilenstein nehmen

**Comment by langerschris** [comment]
fyi übernehem gerade eure Änderungen ins Pflichtenheft

**Comment by johanngoltz** [comment]
Mach ich auch grad :/

**Comment by johanngoltz** [comment]
[Vorschläge von @Sta7e eingepflegt](https://github.com/johanngoltz/sumz-ui/files/2016057/Pflichtenheft.SUMZ.UI_1-3.docx)

**Comment by langerschris** [comment]
Version 1.4
- Änderungen übernommen Punkte 2.3 und 2.4 und 3.8 bitte nochmal prüfen und ggfs gleich im Dokument vernünftig formulieren
[Pflichtenheft.SUMZ.UI_1-4.docx](https://github.com/johanngoltz/sumz-ui/files/2016107/Pflichtenheft.SUMZ.UI_1-4.docx)

**Comment by schaefermichael** [comment]
Andere Teilgruppe 
[20180517_Pflichtenheft_V0.1.docx](https://github.com/johanngoltz/sumz-ui/files/2016491/20180517_Pflichtenheft_V0.1.docx)

**Comment by tomastepa** [comment]
Zusammengeführte Version
[20180518_Pflichtenheft_V1.0.docx](https://github.com/johanngoltz/sumz-ui/files/2018644/20180518_Pflichtenheft_V1.0.docx)
